# Generated by Django 4.1.7 on 2023-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="photos/%y/%m/%d"),
        ),
    ]
